service: api
runtime: python27
instance_class: F2
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - app(\/.*)
  - node_modules
  - public
