service: api
runtime: python27
instance_class: F4
api_version: 1
threadsafe: true
automatic_scaling:
  target_cpu_utilization: 0.8
  max_instances: 2
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: main.app

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - app(\/.*)
  - node_modules
  - public
